# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-04 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axes', '0003_auto_20160322_0929'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessattempt',
            name='request_data',
            field=models.TextField(null=True, verbose_name='REQUEST Data'),
        ),
    ]
